### ISSUE TITLE
哪里配置出错导致出现这个7.0权限问题的

### ISSUE THREAD

**Issue by coolmaye** [TommyLemon/Android-ZBLibrary#20]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10, result=-1, data=Intent { (has extras) }} to activity {com.cathaynav.tradeschoolteacher/zuo.biao.library.ui.SelectPictureActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/com.cathaynav.tradeschoolteacher/image/photo1526372170558.jpg exposed beyond app through ClipData.Item.getUri()
                                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4224)
                                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4267)
                                                                                      at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:163)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6396)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                                   Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/com.cathaynav.tradeschoolteacher/image/photo1526372170558.jpg exposed beyond app through ClipData.Item.getUri()

demo就不会出错，我配置的就会出错

**Comment by TommyLemon** [comment]
把targetSDK改为22，或者试试用下面的方法
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by TommyLemon** [comment]
已解决
https://github.com/TommyLemon/Android-ZBLibrary/commit/f1b2acff0f053cdead36df93f58418db98e81928
